services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack-cpsf
    ports:
      - 4566:4566
    environment:
      - SERVICES=dynamodb,s3,kms
      - DEBUG=1
      - LAMBDA_EXECUTOR=docker
      # set AWS configrations for localstack
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=key
      - AWS_SECRET_ACCESS_KEY=secret
    networks:
      - test-assignment-cpsf
    volumes:
      # provision localstack
      - ./init-scripts:/etc/localstack/init/ready.d
      # share docker with localstack
      - "/var/run/docker.sock:/var/run/docker.sock"

  filestorage-api:
    build:
      context: ./FileStorage
      dockerfile: Dockerfile
    image: filestorage-api:latest
    container_name: filestorage-api
    environment:
      - AWS_ACCESS_KEY_ID=key
      - AWS_SECRET_ACCESS_KEY=secret
      - AWS_REGION=us-east-1
      - AWS_ENDPOINT_URL=http://localstack-cpsf:4566
    ports:
      - 8080:8080
    networks:
      - test-assignment-cpsf
    depends_on:
      - localstack
 
  dynamodb-admin:
     image: aaronshaf/dynamodb-admin
     container_name: dynamodb-admin
     ports:
       - 8001:8001
     environment:
       - DYNAMO_ENDPOINT=http://host.docker.internal:4566
     depends_on:
       - localstack


networks:
  test-assignment-cpsf:
    driver: bridge
